spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee-service/**
          filters:
            - RewritePath=/employee-service/(?<path>.*), /$\{path}
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student-service/**
          filters:
            - RewritePath=/student-service/(?<path>.*), /$\{path}